rules = [
  OrganizeImports,
  RemoveUnused,
]
OrganizeImports {
  groups = [
    "scala."
    "*"
    "scalasql.",
    "typebricks.",
  ]
  blankLines = Auto
  groupedImports = Explode
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  preset = DEFAULT
  targetDialect = Scala3
}